version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5b9z8b9
  build:
    commands:
      - docker build -t sui-crud-web .
  post_build:
    commands:
      - docker tag sui-crud-web:latest public.ecr.aws/y5b9z8b9/sui-crud-web:latest
      - docker push public.ecr.aws/y5b9z8b9/sui-crud-web:latest
      - yum install jq -y
      - ContainerName="php-web"
      - ImageURI=$(cat imageDetail.json | jq -r '.ImageURI')
      - printf '[{"name":"wordpress","imageUri":"public.ecr.aws/y5b9z8b9/sui-crud-web:latest"}]' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|wordpress|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_URI|public.ecr.aws/y5b9z8b9/sui-crud-web:latest|g" imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
